version: 2.1

commands:
  # similar to a function definition print_pipeline_id(caller="Default") => echo << parameters.caller >>
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      caller:
        type: string
        default: "Default"
    steps:
      - run: echo << parameters.caller >> $CIRCLE_WORKFLOW_ID

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack

  add_target_host:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: install workspace depencies
          command: |
            yum install -y tar
            yum install -y gzip
      - run:
          name: get host from aws
          command: |
            echo 'export MY_HOST=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters --region us-east-1 --output text)' >> $BASH_ENV
            source $BASH_ENV
            echo $MY_HOST
      - run:
          name: add host to inventory
          command: |
            echo "${MY_HOST}" >> inventory
            echo "${MY_HOST}" > ~/host.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - host.txt

  configure_infrastructure:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["42:2b:b0:e2:b2:36:58:a8:2c:7d:7c:8a:09:60:f0:b0"]
      - run:
          name: Install dependencies
          command: |
            sudo pip install ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~/
      - run: apk add --update curl
      - run:
          name: smoke test.
          command: |
            MY_HOST=$(cat host.txt)
            URL="${MY_HOST}:3000"
            if curl -s --head ${URL} # test if server is up and running
            then
              return 0
            else
              return 1
            fi

workflows:
  main:
    jobs:
      - create_infrastructure
      - add_target_host:
          requires:
            - create_infrastructure
      - configure_infrastructure:
          requires:
            - add_target_host
      - smoke_test:
          requires:
            - configure_infrastructure
